Add failfast

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -84,7 +84,10 @@ script:
               role=$(sed 's|\.sh$||' <<< $role);
               role=$(sed 's|^roles/||' <<< $role);
               sed -i "s|###|$role|g" .ci/Dockerfile-separateroles;
-              docker build -f .ci/Dockerfile-separateroles .;
+              if ! docker build -f .ci/Dockerfile-separateroles .; then
+                  echo "Failed at $role";
+                  exit 1;
+              fi;
               git checkout .;
           done
       fi
