Add install,sh file

diff --git a/.ci/Dockerfile-separateroles b/.ci/Dockerfile-separateroles
--- a/.ci/Dockerfile-separateroles
+++ b/.ci/Dockerfile-separateroles
@@ -10,4 +10,8 @@ COPY . /src/
 
 RUN wget -q https://github.com/bltavares/kickstart/archive/master.zip
 RUN unzip master.zip
+RUN echo "set -euo pipefail" >> install.sh
+RUN echo "export MYUSER=$USER" >> install.sh
+RUN echo "export MYHOME=$HOME" >> install.sh
+RUN echo "export NO_GPG_VERIFY=1" >> install.sh
 RUN PATH="${PWD}/kickstart-master/bin:${PATH}" DEBUG=1 kickstart local --sudo ###
